### ISSUE TITLE
Make this repo easy to use on custom data

### ISSUE THREAD

**Issue by tr1pzz** [yinboc/liif#1]
Hey, it would be amazing if you had a simple script that allowed running the models on a set of custom input images.
I was able to run test.py on the example datasets, but the dataloaders require a very specific folder structure with LR_bicubic subfolders etc... It's hard to figure out how to simply apply a pretrained model to custom images.

Also, it's not super clear what the best settings are for running this or regular images (of resolution say 250-1000 pixels²) to obtain HD super-resolution images: should you run the model on the full image, or is it better to run it on several crops of the image and tile the result?

**Comment by yinboc** [comment]
Hi. Thanks for your interest in our work!

The current code is still under testing, we will provide further instructions and visualization code in the near future.
For the questions, the folder structure is defined in config files, during testing the model runs on a full image.
