### ISSUE TITLE
stack expects each tensor to be equal size, but got [3, 256, 256] at entry 0 and [3, 144, 144] at entry 1

### ISSUE THREAD

**Issue by x779250919** [yinboc/liif#11]
when I "python test.py --config ./configs/test/test-set5-2.yaml --model edsr-baseline-liif.pth --gpu 0"
it errors that——
stack expects each tensor to be equal size, but got [3, 256, 256] at entry 0 and [3, 144, 144] at entry 1

it means all image should have same shape?

**Comment by yinboc** [comment]
The config `test-set5-2.yaml` has the batch size of 1 and the code above should work, did you follow the setting in the instructions or did you modifiy anything? Also note that the evaluation batch size should be 1 for correct PSNR computation.

**Comment by x779250919** [comment]
oh,my wrong. that works,very thanks!

**Comment by yinboc** [comment]
You're welcome.
