### ISSUE TITLE
Something about Quick Start

### ISSUE THREAD

**Issue by zzhwfy** [yinboc/liif#13]
I use the same 32x32 LR image in your paper and then run quick start to get 20x SR image, but it looks quite blurred TAT. Here is my result:
![input](https://user-images.githubusercontent.com/57525119/104914360-fc3bad00-59c9-11eb-8ddc-2c10a3b49067.png)
![output](https://user-images.githubusercontent.com/57525119/104914369-01006100-59ca-11eb-8a91-7c1c906b13dd.png)
_________________________________________________________________________________________
*running command: python demo.py --input input.png --model rdn-liif.pth --resolution 640,640 --output output.png --gpu 2

**Comment by yinboc** [comment]
That is interesting, could you describe how did you obtain your image? It should work if you try this image:
![input](https://user-images.githubusercontent.com/10364424/104928410-98bb7a80-59dd-11eb-8cc7-c05babb46d28.png)

This image is generated by croping and bicubic resizing from an image (0857.png) in the div2k validation set (i.e. unseen during training). A potential reason could be that your image is "out of training distribution" for some reason, thus the performance is much worse. The "paper-version" LIIF is only trained with bicubic down-sampling, while it is expected to work for the most of natural images, it may be sensitive to artifacts or noises especially for small images.

**Comment by Mofafa** [comment]
I got similar results. @yinboc Could you please upload some example low res images? I am wondering if the MLP weights are really saved in the public weights.

**Comment by yinboc** [comment]
> I got similar results. @yinboc Could you please upload some example low res images? I am wondering if the MLP weights are really saved in the public weights.

The models should work for general natural images, some example inputs can be found on the project website.
Did you "right click">"save image as">"input.png" for the image **I posted above**? It should work well for both edsr-baseline-liif.pth and rdn-liif.pth if you correctly followed the instructions. If not, could you provide your detailed environment and running steps?

**Comment by zzhwfy** [comment]
@yinboc 
Thanks a lot! I get the same result after I use the LR image posted above. The LR image I used before is generated by **nearest** resizing in **PS** from the image **_mo-flower.png_** in your [website](https://yinboc.github.io/liif/) and I think this is the key point. Due to the different degradation process, my LR image has lost more high-frequency information.
Interestingly, I've compared two LR images and just slight pixel-level differences (PSNR: 36.1042; SSIM: 0.9928). but when we super-resolve them, especially in such a large scaling factor (20X), any small difference can lead to enormous decline in visual quality. Besides this, I use **nearest** resizing in **Matlab** to test, the generated LR image is closer (PSNR: 41.5147; SSIM: 0.9991), but the SR image is also quite different.
NTIRE21 SR challenge introduces LR-PSNR to evaluate SR model, I think it does reflect someting important. And the sensitive nature of CNN makes current SR model difficult to handle real scene SR. 

Thank you for your outstanding work! XD 
————————————————————————————————————————————————
Result: (use the same model)

![output-originLR](https://user-images.githubusercontent.com/57525119/105281697-aba19b00-5be7-11eb-8a26-252d6e7415d0.png)

![output-PS](https://user-images.githubusercontent.com/57525119/105281747-c3791f00-5be7-11eb-8c89-ff91943434a4.png)

![output-ML](https://user-images.githubusercontent.com/57525119/105281765-cecc4a80-5be7-11eb-9af2-2fc96d6edabc.png)

**Comment by yinboc** [comment]
Happy to hear that you solved this issue. The down-sampled image could be different to a true natural image, since it may have artifacts or noises which make it out of distribution (and I believe there should be some SR work focusing on this).
Thanks for reporting this interesting observation!
