### ISSUE TITLE
question about detail

### ISSUE THREAD

**Issue by btwbtm** [yinboc/liif#21]
https://github.com/yinboc/liif/blob/68d6164f9c200e44861bb74ad489c60bbff77fbb/models/liif.py#L82
Hi, to my understanding, rel_coord here should be normalized (i.e. in range [-1,1]). Why do you multiply it with feature size? Thx!

**Comment by yinboc** [comment]
Hi, your understanding is correct and this is the normalization. Before this line, "rel_coord" has the range [-1/H, 1/H] and [-1/W, 1/W], where H,W is the shape of the feature map, thus we normalize by multiplication.

**Comment by btwbtm** [comment]
I see. Thx for your reply.

**Comment by DongHwanJang** [comment]
Thank you for the awesome work.
I have a related question.
Don't we need to multiply feat.shape[-1]  rather than feat.shape[-2] since we are gonna flip the coordinate at the grid_sample function? 
The filp operation is quite confusing. Your advice will be of great help.
Thank you in advance :)

**Comment by DongHwanJang** [comment]
> Thank you for the awesome work.
> I have a related question.
> Don't we need to multiply feat.shape[-1] rather than feat.shape[-2] since we are gonna flip the coordinate at the grid_sample function?
> The filp operation is quite confusing. Your advice will be of great help.
> Thank you in advance :)

It was because of the nature of grid_sample function of PyTorch. The coordinate [-1, 1] is not the left-bottom corner, but right-top corner when we perform grid_sample.

**Comment by shkarupa-alex** [comment]
> Hi, your understanding is correct and this is the normalization. Before this line, "rel_coord" has the range [-1/H, 1/H] and [-1/W, 1/W], where H,W is the shape of the feature map, thus we normalize by multiplication.

Found my mistake in previous version of this comment. You were right, sorry.

**Comment by XiaoyuShi97** [comment]
你好，这是石晓宇的邮箱。我会尽快处理该邮件
