### ISSUE TITLE
L1 loss

### ISSUE THREAD

**Issue by Tsingularity** [yinboc/liif#22]
Hi, thanks for the great work!

I am just curious that, is there any specific or special reason for using L1 loss instead of L2 loss during training? Because I feel like L2 loss matches better with the PSNR metric?

Thanks!

**Comment by yinboc** [comment]
Thanks for you interest in our work! Using L1 loss is an interesting common practice in recent SR works, it seems to work better than L2 (even if L2 looks closer to PSNR). For example, it is discussed in https://arxiv.org/pdf/1707.02921.pdf .
