### ISSUE TITLE
can not download split.json

### ISSUE THREAD

**Issue by bring728** [yinboc/liif#24]
![image](https://user-images.githubusercontent.com/24850969/117927525-46f48280-b335-11eb-84cb-af9fea60117b.png)

I am trying to download split.json in the paragraph above, but I have an error. Can you solve it?

**Comment by yinboc** [comment]
It is a dropbox link and seems to work for me. I uploaded it below:

[split.zip](https://github.com/yinboc/liif/files/6470348/split.zip)
