### ISSUE TITLE
Sorry to disturb.But pretrained models in Dropbox is not available for me, could you please upload a GoogleDrive link as alternate?

### ISSUE THREAD

**Issue by AstomMars** [yinboc/liif#4]
Or could any enthusiastic guy provide assistance for me? Thanks a lot.

**Comment by yinboc** [comment]
Could you provide a detailed reason why it is not available? Both manual download and bash download should work.

**Comment by AstomMars** [comment]
Appreciate for your reply.
Due to China's firewall, I can't download them from dropbox manually. 
And I don't find where bash download is... Only find some urls in models/edsr.py, which can not be loaded by network.

**Comment by yinboc** [comment]
You're welcome.
I updated the Google Drive download links in the instructions. For Dropbox's bash download, I think a `wget` should work (you may google for more details).

**Comment by AstomMars** [comment]
Gratitude is beyond words. I have downloaded them.
