### ISSUE TITLE
[not code issues]other related

### ISSUE THREAD

**Issue by huaji0353** [yinboc/liif#6]
Add related

Ideas:
[represent an image using hilbert-curve](https://www.3blue1brown.com/videos-blog/2017/5/26/the-hilbert-curve)
[Image Generators with Conditionally-Independent Pixel Synthesis](https://arxiv.org/abs/2011.13775)
[represent an image using color 3D point cloud](http://yig.github.io/image-rgb-in-3D/)

presentation of video:
[powers of ten](https://www.youtube.com/results?search_query=powers+of+ten)
[Universe Size Comparison](https://www.youtube.com/results?search_query=Universe+Size+Comparison)
[Scale of the Universe](https://www.google.com/search?q=Scale+of+the+Universe)
[IllustrisTNG Sim Project](https://www.tng-project.org/)

**Comment by yinboc** [comment]
Image Generators with Conditionally-Independent Pixel Synthesis is concurrent to ours. (and it is also an interesting work)
There are many related fields to our work, each of these fields contains maybe hundreds of interesting works, which we unfortunately do not have enough time and space to acknowledge all of them in this draft.
